"""add updated_at to resumes

Revision ID: 5ddac2e0532f
Revises: 001_initial_schema
Create Date: 2026-07-26 11:14:48.974301+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5ddac2e0532f'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_history', 'resume_id',
               existing_type=sa.UUID(),
               comment='The resume that was analysed',
               existing_nullable=False)
    op.alter_column('analysis_history', 'job_description_id',
               existing_type=sa.UUID(),
               comment='The JD the resume was matched against',
               existing_nullable=False)
    op.alter_column('analysis_history', 'ats_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='ATS score out of 100',
               existing_nullable=True)
    op.alter_column('analysis_history', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Semantic similarity score 0–100 (FAISS cosine)',
               existing_nullable=True)
    op.alter_column('analysis_history', 'keyword_match_count',
               existing_type=sa.INTEGER(),
               comment='Number of JD keywords found in resume',
               existing_nullable=True)
    op.alter_column('analysis_history', 'missing_skills_json',
               existing_type=sa.TEXT(),
               comment='JSON list of skills present in JD but missing from resume',
               existing_nullable=True)
    op.alter_column('analysis_history', 'matched_skills_json',
               existing_type=sa.TEXT(),
               comment='JSON list of matched skills',
               existing_nullable=True)
    op.alter_column('analysis_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending | processing | completed | failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('analysis_history', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error details if status=failed',
               existing_nullable=True)
    op.alter_column('analysis_history', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When analysis finished (null if still running)',
               existing_nullable=True)
    op.add_column('job_descriptions', sa.Column('required_skills', sa.Text(), nullable=True, comment='Extracted required skills (JSON-serialized list)'))
    op.add_column('job_descriptions', sa.Column('experience_level', sa.String(length=50), nullable=True, comment='e.g., Entry, Mid, Senior, Lead'))
    op.add_column('job_descriptions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('job_descriptions', 'user_id',
               existing_type=sa.UUID(),
               comment='User who created this job description',
               existing_nullable=False)
    op.alter_column('job_descriptions', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Job title (e.g., Senior Backend Engineer)',
               existing_nullable=False)
    op.alter_column('job_descriptions', 'company',
               existing_type=sa.VARCHAR(length=255),
               comment='Hiring company name',
               existing_nullable=True)
    op.alter_column('job_descriptions', 'description',
               existing_type=sa.TEXT(),
               comment='Full job description text',
               existing_nullable=False)
    op.create_index('ix_jd_title', 'job_descriptions', ['title'], unique=False)
    op.create_table_comment(
        'job_descriptions',
        'Job descriptions submitted by users',
        existing_comment='Job descriptions uploaded by users for analysis',
        schema=None
    )
    op.alter_column('reports', 'analysis_id',
               existing_type=sa.UUID(),
               comment='The analysis run this report was generated from',
               existing_nullable=False)
    op.alter_column('reports', 'strengths',
               existing_type=sa.TEXT(),
               comment='JSON list of resume strengths identified by Gemini',
               existing_nullable=True)
    op.alter_column('reports', 'weaknesses',
               existing_type=sa.TEXT(),
               comment='JSON list of weaknesses / areas to improve',
               existing_nullable=True)
    op.alter_column('reports', 'recommendations',
               existing_type=sa.TEXT(),
               comment='JSON list of AI-generated improvement recommendations',
               existing_nullable=True)
    op.alter_column('reports', 'improved_resume',
               existing_type=sa.TEXT(),
               comment='JSON map of original → improved bullet points (STAR format)',
               existing_nullable=True)
    op.alter_column('reports', 'interview_tips',
               existing_type=sa.TEXT(),
               comment='JSON list of interview preparation tips',
               existing_nullable=True)
    op.alter_column('reports', 'career_roadmap',
               existing_type=sa.TEXT(),
               comment='JSON structured career development roadmap',
               existing_nullable=True)
    op.alter_column('reports', 'skill_gaps',
               existing_type=sa.TEXT(),
               comment='JSON map of high/medium/future priority missing skills',
               existing_nullable=True)
    op.alter_column('reports', 'keyword_suggestions',
               existing_type=sa.TEXT(),
               comment='JSON list of missing ATS keywords to add',
               existing_nullable=True)
    op.alter_column('reports', 'section_feedback',
               existing_type=sa.TEXT(),
               comment='JSON map of per-section feedback (Experience, Education, etc.)',
               existing_nullable=True)
    op.alter_column('reports', 'recruiter_verdict',
               existing_type=sa.TEXT(),
               comment='Short plain-text recruiter-style final verdict',
               existing_nullable=True)
    op.alter_column('reports', 'full_report_json',
               existing_type=sa.TEXT(),
               comment='Full structured JSON report blob — consumed by frontend',
               existing_nullable=True)
    op.add_column('resume_embeddings', sa.Column('embedding_reference', sa.String(length=512), nullable=False, comment='FAISS internal index ID or disk path to the .npy file'))
    op.add_column('resume_embeddings', sa.Column('model_name', sa.String(length=100), nullable=False, comment='Sentence Transformer model used to generate this embedding'))
    op.add_column('resume_embeddings', sa.Column('vector_dimension', sa.Integer(), nullable=False, comment='Dimensionality of the embedding vector'))
    op.alter_column('resume_embeddings', 'resume_id',
               existing_type=sa.UUID(),
               comment='Resume whose text was embedded',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='For multi-chunk resumes: which chunk this embedding represents',
               existing_nullable=False)
    op.drop_index('ix_embeddings_resume_id', table_name='resume_embeddings')
    op.create_index('ix_embedding_model', 'resume_embeddings', ['model_name'], unique=False)
    op.create_index('ix_embedding_resume_id', 'resume_embeddings', ['resume_id'], unique=False)
    op.create_table_comment(
        'resume_embeddings',
        'FAISS embedding references for each resume chunk',
        existing_comment='Chunk embeddings for RAG pipeline',
        schema=None
    )
    op.drop_column('resume_embeddings', 'embedding_model')
    op.drop_column('resume_embeddings', 'chunk_text')
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('resumes', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner user of this resume',
               existing_nullable=False)
    op.alter_column('resumes', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Original uploaded filename (e.g. my_resume.pdf)',
               existing_nullable=False)
    op.alter_column('resumes', 'stored_path',
               existing_type=sa.VARCHAR(length=512),
               comment='Filesystem path where the file is stored',
               existing_nullable=False)
    op.alter_column('resumes', 'file_type',
               existing_type=sa.VARCHAR(length=10),
               comment='File extension: pdf, docx, or txt',
               existing_nullable=False)
    op.alter_column('resumes', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='File size in bytes for validation auditing')
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.TEXT(),
               comment='Full extracted text from the resume document',
               existing_nullable=True)
    op.alter_column('resumes', 'candidate_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('resumes', 'candidate_phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('resumes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag — do not purge rows',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_resumes_candidate_email', 'resumes', ['candidate_email'], unique=False)
    op.create_table_comment(
        'resumes',
        'Uploaded resume documents with parsed content',
        existing_comment='Uploaded resume files and their parsed content',
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='Unique user identifier (UUID v4)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='Full display name',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique email address used for login',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt-hashed password — never store plaintext',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft-disable account without deleting',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_table_comment(
        'users',
        'Application user accounts',
        existing_comment='Platform user accounts',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Platform user accounts',
        existing_comment='Application user accounts',
        schema=None
    )
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft-disable account without deleting',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt-hashed password — never store plaintext',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique email address used for login',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Full display name',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique user identifier (UUID v4)',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_table_comment(
        'resumes',
        'Uploaded resume files and their parsed content',
        existing_comment='Uploaded resume documents with parsed content',
        schema=None
    )
    op.drop_index('ix_resumes_candidate_email', table_name='resumes')
    op.alter_column('resumes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag — do not purge rows',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('resumes', 'candidate_phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('resumes', 'candidate_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full extracted text from the resume document',
               existing_nullable=True)
    op.alter_column('resumes', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='File size in bytes for validation auditing')
    op.alter_column('resumes', 'file_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='File extension: pdf, docx, or txt',
               existing_nullable=False)
    op.alter_column('resumes', 'stored_path',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Filesystem path where the file is stored',
               existing_nullable=False)
    op.alter_column('resumes', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original uploaded filename (e.g. my_resume.pdf)',
               existing_nullable=False)
    op.alter_column('resumes', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner user of this resume',
               existing_nullable=False)
    op.drop_column('resumes', 'updated_at')
    op.add_column('resume_embeddings', sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('resume_embeddings', sa.Column('embedding_model', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_table_comment(
        'resume_embeddings',
        'Chunk embeddings for RAG pipeline',
        existing_comment='FAISS embedding references for each resume chunk',
        schema=None
    )
    op.drop_index('ix_embedding_resume_id', table_name='resume_embeddings')
    op.drop_index('ix_embedding_model', table_name='resume_embeddings')
    op.create_index('ix_embeddings_resume_id', 'resume_embeddings', ['resume_id'], unique=False)
    op.alter_column('resume_embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='For multi-chunk resumes: which chunk this embedding represents',
               existing_nullable=False)
    op.alter_column('resume_embeddings', 'resume_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Resume whose text was embedded',
               existing_nullable=False)
    op.drop_column('resume_embeddings', 'vector_dimension')
    op.drop_column('resume_embeddings', 'model_name')
    op.drop_column('resume_embeddings', 'embedding_reference')
    op.alter_column('reports', 'full_report_json',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full structured JSON report blob — consumed by frontend',
               existing_nullable=True)
    op.alter_column('reports', 'recruiter_verdict',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Short plain-text recruiter-style final verdict',
               existing_nullable=True)
    op.alter_column('reports', 'section_feedback',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON map of per-section feedback (Experience, Education, etc.)',
               existing_nullable=True)
    op.alter_column('reports', 'keyword_suggestions',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of missing ATS keywords to add',
               existing_nullable=True)
    op.alter_column('reports', 'skill_gaps',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON map of high/medium/future priority missing skills',
               existing_nullable=True)
    op.alter_column('reports', 'career_roadmap',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON structured career development roadmap',
               existing_nullable=True)
    op.alter_column('reports', 'interview_tips',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of interview preparation tips',
               existing_nullable=True)
    op.alter_column('reports', 'improved_resume',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON map of original → improved bullet points (STAR format)',
               existing_nullable=True)
    op.alter_column('reports', 'recommendations',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of AI-generated improvement recommendations',
               existing_nullable=True)
    op.alter_column('reports', 'weaknesses',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of weaknesses / areas to improve',
               existing_nullable=True)
    op.alter_column('reports', 'strengths',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of resume strengths identified by Gemini',
               existing_nullable=True)
    op.alter_column('reports', 'analysis_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The analysis run this report was generated from',
               existing_nullable=False)
    op.create_table_comment(
        'job_descriptions',
        'Job descriptions uploaded by users for analysis',
        existing_comment='Job descriptions submitted by users',
        schema=None
    )
    op.drop_index('ix_jd_title', table_name='job_descriptions')
    op.alter_column('job_descriptions', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full job description text',
               existing_nullable=False)
    op.alter_column('job_descriptions', 'company',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hiring company name',
               existing_nullable=True)
    op.alter_column('job_descriptions', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Job title (e.g., Senior Backend Engineer)',
               existing_nullable=False)
    op.alter_column('job_descriptions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created this job description',
               existing_nullable=False)
    op.drop_column('job_descriptions', 'updated_at')
    op.drop_column('job_descriptions', 'experience_level')
    op.drop_column('job_descriptions', 'required_skills')
    op.alter_column('analysis_history', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When analysis finished (null if still running)',
               existing_nullable=True)
    op.alter_column('analysis_history', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error details if status=failed',
               existing_nullable=True)
    op.alter_column('analysis_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending | processing | completed | failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('analysis_history', 'matched_skills_json',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of matched skills',
               existing_nullable=True)
    op.alter_column('analysis_history', 'missing_skills_json',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of skills present in JD but missing from resume',
               existing_nullable=True)
    op.alter_column('analysis_history', 'keyword_match_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of JD keywords found in resume',
               existing_nullable=True)
    op.alter_column('analysis_history', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Semantic similarity score 0–100 (FAISS cosine)',
               existing_nullable=True)
    op.alter_column('analysis_history', 'ats_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='ATS score out of 100',
               existing_nullable=True)
    op.alter_column('analysis_history', 'job_description_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The JD the resume was matched against',
               existing_nullable=False)
    op.alter_column('analysis_history', 'resume_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The resume that was analysed',
               existing_nullable=False)
    # ### end Alembic commands ###
