"""remove_user_id

Revision ID: a4392c6c1524
Revises: 668d45adb49c
Create Date: 2026-08-06 16:55:01.727325+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a4392c6c1524'
down_revision: Union[str, None] = '668d45adb49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jd_user_id', table_name='job_descriptions')
    op.drop_constraint('job_descriptions_user_id_fkey', 'job_descriptions', type_='foreignkey')
    op.drop_column('job_descriptions', 'user_id')
    op.drop_index('ix_resumes_user_id', table_name='resumes')
    op.drop_constraint('resumes_user_id_fkey', 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'user_id')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='Owner user of this resume'))
    op.create_foreign_key('resumes_user_id_fkey', 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_resumes_user_id', 'resumes', ['user_id'], unique=False)
    op.add_column('job_descriptions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='User who created this job description'))
    op.create_foreign_key('job_descriptions_user_id_fkey', 'job_descriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_jd_user_id', 'job_descriptions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='Unique user identifier (UUID v4)'),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False, comment='Full display name'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Unique email address used for login'),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Bcrypt-hashed password — never store plaintext'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Soft-disable account without deleting'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    comment='Application user accounts'
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###
