"""remove_auth

Revision ID: 668d45adb49c
Revises: 5ddac2e0532f
Create Date: 2026-08-05 14:13:56.477589+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '668d45adb49c'
down_revision: Union[str, None] = '5ddac2e0532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
