"""
Gemini Prompt Templates
========================
Centralized prompt strings for every AI task.
Keeping prompts in one module makes tuning and versioning easy.

Note on ATS scoring:
    The ATS numeric score is NEVER generated by Gemini.
    Gemini only produces explanations and suggestions.
"""

from typing import List


class PromptTemplates:
    """
    Static prompt templates for all Gemini API calls.

    Each method returns a fully formatted prompt string ready to send.
    All prompts instruct Gemini to return valid JSON for reliable parsing.
    """

    @staticmethod
    def full_analysis(resume_text: str, job_description: str, rag_context: str) -> str:
        return f"""
You are an expert technical recruiter and career coach with 15+ years of experience.

Analyze the following resume against the job description.
Use the RETRIEVED CONTEXT (semantically similar resume sections retrieved via FAISS) to enrich your analysis.

RETRIEVED CONTEXT (top-k chunks from FAISS semantic retrieval):
{rag_context}

RESUME:
{resume_text[:3000]}

JOB DESCRIPTION:
{job_description[:2000]}

Return ONLY a valid JSON object with this exact structure:
{{
  "strengths": ["strength1", "strength2", "strength3"],
  "weaknesses": ["weakness1", "weakness2"],
  "career_advice": "Detailed paragraph of career advice tailored to this role",
  "interview_tips": ["tip1", "tip2", "tip3", "tip4", "tip5"],
  "career_roadmap": ["step1", "step2", "step3", "step4"],
  "recruiter_verdict": "One paragraph final verdict as a technical recruiter",
  "certification_recommendations": ["cert1", "cert2"],
  "project_recommendations": ["project idea 1 that fills skill gap", "project idea 2"]
}}
"""

    @staticmethod
    def ats_explanation(resume_text: str, job_description: str, computed_score: float) -> str:
        """
        Prompt for Gemini to EXPLAIN an already-computed ATS score.
        Gemini must NOT recompute or override the numeric score.
        """
        return f"""
You are an ATS (Applicant Tracking System) expert and resume coach.

A rule-based ATS engine has already computed a score of {computed_score:.1f}/100 for this resume.

Your task is to:
1. Explain WHY the resume received this score
2. Identify the weakest areas
3. Provide specific, actionable improvement recommendations

RESUME:
{resume_text[:3000]}

JOB DESCRIPTION:
{job_description[:2000]}

Return ONLY a valid JSON object:
{{
  "score_explanation": "Why this resume scored {computed_score:.1f}/100",
  "weak_areas": "The main areas that lowered the score",
  "recommendations": [
    "Specific recommendation 1 with exact action to take",
    "Specific recommendation 2",
    "Specific recommendation 3",
    "Specific recommendation 4",
    "Specific recommendation 5"
  ]
}}

IMPORTANT: Do NOT suggest a different score. The score of {computed_score:.1f} is final.
"""

    @staticmethod
    def improve_bullets(experience_bullets: List[str], job_description: str) -> str:
        bullets_text = "\n".join(f"- {b}" for b in experience_bullets[:10])
        return f"""
You are a professional resume writer specializing in STAR-format bullet points.

Rewrite these resume bullets to be stronger, more impactful, and quantified where possible.
Target role context: {job_description[:500]}

ORIGINAL BULLETS:
{bullets_text}

Rules:
- Use STAR format (Situation/Task → Action → Result)
- Start each bullet with a strong action verb
- Add quantified metrics where plausible (%, $, users, time saved)
- Keep each bullet to 1-2 lines
- Make impact explicit

Return ONLY a valid JSON array:
[
  {{
    "original": "original bullet text",
    "improved": "Redesigned X system using Y technology, reducing Z by 35% and improving A for B users",
    "explanation": "Why this improvement is stronger"
  }}
]
"""

    @staticmethod
    def skill_gap(resume_skills: List[str], job_description: str) -> str:
        skills_str = ", ".join(resume_skills[:30])
        return f"""
You are a technical hiring manager performing a skill gap analysis.

CANDIDATE SKILLS: {skills_str}

JOB DESCRIPTION:
{job_description[:2000]}

Identify skill gaps and create a prioritized learning roadmap.

Return ONLY a valid JSON object:
{{
  "job_skills": ["skill1", "skill2"],
  "high_priority_missing": ["critical_skill1", "critical_skill2"],
  "medium_priority_missing": ["nice_to_have1", "nice_to_have2"],
  "future_skills": ["emerging_tech1", "emerging_tech2"],
  "learning_roadmap": [
    {{"skill": "Kubernetes", "resource": "CKA Certification", "timeline": "3 months", "priority": "High"}},
    {{"skill": "GraphQL", "resource": "Apollo GraphQL Docs + Build a project", "timeline": "1 month", "priority": "Medium"}}
  ]
}}
"""

    @staticmethod
    def section_feedback(resume_text: str, job_description: str) -> str:
        return f"""
You are a professional resume reviewer. Provide section-by-section feedback.

RESUME:
{resume_text[:3000]}

JOB DESCRIPTION (for context):
{job_description[:1000]}

Return ONLY a valid JSON object:
{{
  "sections": [
    {{
      "section": "Summary",
      "score": 7.5,
      "feedback": "Your summary is decent but lacks specificity...",
      "suggestions": ["Add years of experience", "Mention key technologies"]
    }},
    {{
      "section": "Experience",
      "score": 6.0,
      "feedback": "Bullets lack quantification...",
      "suggestions": ["Add metrics", "Use stronger action verbs"]
    }},
    {{
      "section": "Skills",
      "score": 8.0,
      "feedback": "Good skills section...",
      "suggestions": ["Add cloud technologies"]
    }},
    {{
      "section": "Education",
      "score": 8.5,
      "feedback": "Education section is well formatted.",
      "suggestions": []
    }},
    {{
      "section": "Projects",
      "score": 5.0,
      "feedback": "Projects section needs more technical depth.",
      "suggestions": ["Add tech stack", "Add GitHub links", "Describe impact"]
    }}
  ],
  "overall_verdict": "Overall assessment paragraph",
  "recruiter_impression": "What a recruiter would think in 6 seconds"
}}
"""

    @staticmethod
    def keyword_optimizer(resume_text: str, job_description: str) -> str:
        return f"""
You are an ATS keyword optimization expert.

RESUME:
{resume_text[:2000]}

JOB DESCRIPTION:
{job_description[:2000]}

Identify missing keywords and suggest where to insert them.

Return ONLY a valid JSON object:
{{
  "missing_ats_keywords": ["REST APIs", "microservices", "CI/CD"],
  "industry_terms": ["distributed systems", "system design"],
  "action_verbs": ["architected", "optimized", "spearheaded", "orchestrated"],
  "modern_technologies": ["Kubernetes", "Terraform", "Apache Kafka"],
  "insertion_suggestions": [
    {{"keyword": "REST APIs", "suggested_placement": "Skills section or Experience bullets"}},
    {{"keyword": "CI/CD", "suggested_placement": "Add to DevOps bullet in Experience"}}
  ]
}}
"""

    @staticmethod
    def match_explanation(
        resume_text: str,
        job_description: str,
        similarity_pct: float,
        matching_skills: List[str],
        missing_skills: List[str],
    ) -> str:
        """Prompt for Gemini to explain the match result with per-category context."""
        return f"""
You are a technical recruiter explaining a semantic similarity analysis.

The AI system computed a {similarity_pct:.1f}% overall match between this resume and job description.

Matching skills: {', '.join(matching_skills[:10]) or 'None detected'}
Missing skills: {', '.join(missing_skills[:10]) or 'None detected'}

RESUME (excerpt):
{resume_text[:2000]}

JOB DESCRIPTION (excerpt):
{job_description[:1500]}

Provide detailed per-category explanations.

Return ONLY a valid JSON object:
{{
  "experience_match_explanation": "Why experience aligns or doesn't",
  "education_match_explanation": "Degree relevance explanation",
  "keyword_match_explanation": "Keyword coverage analysis",
  "overall_verdict": "One paragraph overall match verdict",
  "improvement_priority": ["Most important thing to fix first", "Second priority", "Third priority"]
}}
"""
